repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix"]
      - id: check-toml
      - id: debug-statements
      - id: check-docstring-first

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.14.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      - id: ruff-format

  - repo: https://github.com/psf/black
    rev: 25.9.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or:
          [javascript, jsx, ts, tsx, json, css, scss, html, markdown, yaml]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.38.0
    hooks:
      - id: eslint
        files: \.(js|jsx)$
        types: [file]
