name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Validate release tag
        run: |
          # Extract version (remove refs/tags/v)
          VERSION="${GITHUB_REF#refs/tags/v}"

          # Check if version follows semantic versioning
          if ! echo "$VERSION" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+$'; then
            echo "Version '$VERSION' does not follow semantic versioning"
            exit 1
          fi

          echo "Version '$VERSION' is valid."

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
